#!/bin/sh

NAME=$(sed -n -e 's/^.*Name = //p' /etc/tinc/vpn/tinc.conf)
IP=$(sed -n -e 's/^.*Subnet = //p' /etc/tinc/vpn/hosts/$NAME)
IP=$(echo $IP | sed 's|\(.*\)/.*|\1|')
SUBNET=$(echo $IP | cut -d'.' -f1-3)
SUBNET=$(echo "${SUBNET}.0/24")

ip route del $SUBNET dev $INTERFACE
ip addr del $IP dev $INTERFACE
ip link set $INTERFACE down
