#!/bin/sh

NAME=$(sed -n -e 's/^.*Name = //p' /etc/tinc/vpn/tinc.conf)
IP=$(sed -n -e 's/^.*Subnet = //p' /etc/tinc/vpn/hosts/$NAME)
SUBNET=$(echo $IP | cut -d'.' -f1-3)
SUBNET=$(echo "${SUBNET}.0/24")

ip link set $INTERFACE up
ip addr add $IP dev $INTERFACE
ip route add $SUBNET dev $INTERFACE